
services:
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://time_manager_app_user:lCIYrTNiuwnqGSddK1yWBawURGPe0l1G@dpg-cs33tdd6l47c73e94tjg-a.frankfurt-postgres.render.com/time_manager_app
      - PORT=4000
      - SECRET_KEY_BASE=yV7HrHRPXcpv+hbFHMiUI9gZVejMdwrE5wOoKVhbb8/AY4YrLnFNRp2CjsyToDJc

  frontend:
    build: ./web_interfaces
    ports:
      - "8080:80"
    depends_on: 
      - backend
    environment: 
      - TIME_MANAGER_APP_URL=http://localhost:4000/api

volumes:
  pgdata: